// Generated by Kekboard Warrior
// Preset: waveloop-2
// Device: Corne Choc v4 — Right Half (crkbd/rev4_0/standard)
// Generated: 2026-03-30T15:22:14.690Z
//
// Layer colors:
//   layer 0: base — #e0f5ea
//   layer 1: layer 1 — #e0e8f8
//   layer 2: layer 2 — #e0e8f8
//   layer 3: layer 3 — #e0e8f8

#include QMK_KEYBOARD_H

// ── Combos ──
const uint16_t PROGMEM boot_combo[] = {JS_22, JS_21, JS_0, JS_1, COMBO_END};
combo_t key_combos[] = {
    COMBO(boot_combo, QK_BOOT), // bootloader
};

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3_ex2(  // base
        // Left: row0(6) + ex1
        JS_7, JS_6, JS_5, JS_4, JS_3, JS_2, JS_0,
        // Right: ex1 + row0(6)
        KC_R, KC_ENTER, KC_RIGHT, KC_3, KC_6, KC_F7, KC_F11,
        // Left: row1(6) + ex2
        JS_13, JS_12, JS_11, JS_10, JS_9, JS_8, JS_1,
        // Right: ex2 + row1(6)
        KC_W, KC_UP, KC_DOWN, KC_2, KC_5, KC_F6, KC_F10,
        // Left: row2(6)
        JS_19, JS_18, JS_17, JS_16, JS_15, JS_14,
        // Right: row2(6)
        KC_ESCAPE, KC_LEFT, KC_1, KC_4, KC_F5, KC_F9,
        // Left: thumb(3)
        JS_22, JS_21, JS_20,
        // Right: thumb(3)
        KC_SPACE, MO(2), MO(1)
    ),

    [1] = LAYOUT_split_3x6_3_ex2(  // layer 1
        // Left: row0(6) + ex1
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: ex1 + row0(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Left: row1(6) + ex2
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: ex2 + row1(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Left: row2(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: row2(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Left: thumb(3)
        KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: thumb(3)
        KC_TRNS, KC_TRNS, KC_TRNS
    ),

    [2] = LAYOUT_split_3x6_3_ex2(  // layer 2
        // Left: row0(6) + ex1
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: ex1 + row0(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Left: row1(6) + ex2
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: ex2 + row1(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Left: row2(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: row2(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Left: thumb(3)
        KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: thumb(3)
        KC_TRNS, KC_TRNS, KC_TRNS
    ),

    [3] = LAYOUT_split_3x6_3_ex2(  // layer 3
        // Left: row0(6) + ex1
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: ex1 + row0(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Left: row1(6) + ex2
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: ex2 + row1(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Left: row2(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: row2(6)
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // Left: thumb(3)
        KC_TRNS, KC_TRNS, KC_TRNS,
        // Right: thumb(3)
        KC_TRNS, KC_TRNS, KC_TRNS
    )
};
// clang-format on
