// Generated by Kekboard Warrior
// Preset: waveloop-midi
// Device: Corne Choc v4 — Right Half (crkbd/rev4_0/standard)
// Generated: 2026-03-30T23:07:34.676Z
//
// Layer colors:
//   layer 0: base — #ffffff
//   layer 1: fx — #ff0000
//   layer 2: tape — #00fffb
// Bootloader: hold MO(2) [7,4] + press 7,3

#include QMK_KEYBOARD_H

#include "qmk_midi.h"

// ── MIDI CC handler ──
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    bool pressed = record->event.pressed;
    uint8_t layer = get_highest_layer(layer_state);
        if (record->event.key.row == 7 && record->event.key.col == 3 && layer == 0) {
            midi_send_cc(&midi_device, 0, 1, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 6 && layer == 0) {
            midi_send_cc(&midi_device, 0, 2, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 6 && layer == 0) {
            midi_send_cc(&midi_device, 0, 3, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 0 && layer == 0) {
            midi_send_cc(&midi_device, 0, 4, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 1 && layer == 0) {
            midi_send_cc(&midi_device, 0, 5, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 2 && layer == 0) {
            midi_send_cc(&midi_device, 0, 6, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 3 && layer == 0) {
            midi_send_cc(&midi_device, 0, 7, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 4 && layer == 0) {
            midi_send_cc(&midi_device, 0, 8, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 5 && layer == 0) {
            midi_send_cc(&midi_device, 0, 9, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 0 && layer == 0) {
            midi_send_cc(&midi_device, 0, 10, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 1 && layer == 0) {
            midi_send_cc(&midi_device, 0, 11, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 2 && layer == 0) {
            midi_send_cc(&midi_device, 0, 12, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 3 && layer == 0) {
            midi_send_cc(&midi_device, 0, 13, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 4 && layer == 0) {
            midi_send_cc(&midi_device, 0, 14, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 5 && layer == 0) {
            midi_send_cc(&midi_device, 0, 15, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 0 && layer == 0) {
            midi_send_cc(&midi_device, 0, 16, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 1 && layer == 0) {
            midi_send_cc(&midi_device, 0, 17, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 2 && layer == 0) {
            midi_send_cc(&midi_device, 0, 18, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 3 && layer == 0) {
            midi_send_cc(&midi_device, 0, 19, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 4 && layer == 0) {
            midi_send_cc(&midi_device, 0, 20, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 5 && layer == 0) {
            midi_send_cc(&midi_device, 0, 21, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 7 && record->event.key.col == 3 && layer == 1) {
            midi_send_cc(&midi_device, 0, 22, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 6 && layer == 1) {
            midi_send_cc(&midi_device, 0, 23, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 6 && layer == 1) {
            midi_send_cc(&midi_device, 0, 24, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 0 && layer == 1) {
            midi_send_cc(&midi_device, 0, 25, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 1 && layer == 1) {
            midi_send_cc(&midi_device, 0, 26, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 2 && layer == 1) {
            midi_send_cc(&midi_device, 0, 27, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 3 && layer == 1) {
            midi_send_cc(&midi_device, 0, 28, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 4 && layer == 1) {
            midi_send_cc(&midi_device, 0, 29, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 5 && layer == 1) {
            midi_send_cc(&midi_device, 0, 30, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 0 && layer == 1) {
            midi_send_cc(&midi_device, 0, 31, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 1 && layer == 1) {
            midi_send_cc(&midi_device, 0, 32, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 2 && layer == 1) {
            midi_send_cc(&midi_device, 0, 33, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 3 && layer == 1) {
            midi_send_cc(&midi_device, 0, 34, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 4 && layer == 1) {
            midi_send_cc(&midi_device, 0, 35, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 5 && layer == 1) {
            midi_send_cc(&midi_device, 0, 36, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 0 && layer == 1) {
            midi_send_cc(&midi_device, 0, 37, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 1 && layer == 1) {
            midi_send_cc(&midi_device, 0, 38, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 2 && layer == 1) {
            midi_send_cc(&midi_device, 0, 39, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 3 && layer == 1) {
            midi_send_cc(&midi_device, 0, 40, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 4 && layer == 1) {
            midi_send_cc(&midi_device, 0, 41, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 5 && layer == 1) {
            midi_send_cc(&midi_device, 0, 42, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 6 && layer == 2) {
            midi_send_cc(&midi_device, 0, 44, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 6 && layer == 2) {
            midi_send_cc(&midi_device, 0, 45, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 0 && layer == 2) {
            midi_send_cc(&midi_device, 0, 46, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 1 && layer == 2) {
            midi_send_cc(&midi_device, 0, 47, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 2 && layer == 2) {
            midi_send_cc(&midi_device, 0, 48, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 3 && layer == 2) {
            midi_send_cc(&midi_device, 0, 49, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 4 && layer == 2) {
            midi_send_cc(&midi_device, 0, 50, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 4 && record->event.key.col == 5 && layer == 2) {
            midi_send_cc(&midi_device, 0, 51, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 0 && layer == 2) {
            midi_send_cc(&midi_device, 0, 52, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 1 && layer == 2) {
            midi_send_cc(&midi_device, 0, 53, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 2 && layer == 2) {
            midi_send_cc(&midi_device, 0, 54, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 3 && layer == 2) {
            midi_send_cc(&midi_device, 0, 55, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 4 && layer == 2) {
            midi_send_cc(&midi_device, 0, 56, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 5 && record->event.key.col == 5 && layer == 2) {
            midi_send_cc(&midi_device, 0, 57, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 0 && layer == 2) {
            midi_send_cc(&midi_device, 0, 58, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 1 && layer == 2) {
            midi_send_cc(&midi_device, 0, 59, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 2 && layer == 2) {
            midi_send_cc(&midi_device, 0, 60, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 3 && layer == 2) {
            midi_send_cc(&midi_device, 0, 61, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 4 && layer == 2) {
            midi_send_cc(&midi_device, 0, 62, pressed ? 127 : 0);
            return false;
        }
        if (record->event.key.row == 6 && record->event.key.col == 5 && layer == 2) {
            midi_send_cc(&midi_device, 0, 63, pressed ? 127 : 0);
            return false;
        }
    return true;
}

// ── Per-layer RGB colors ──
bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    uint8_t r = 0, g = 0, b = 0;
    switch (get_highest_layer(layer_state)) {
        case 0: r=255; g=255; b=255; break; // base
        case 1: r=255; g=0; b=0; break; // fx
        case 2: r=0; g=255; b=251; break; // tape
    }
    for (uint8_t i = led_min; i < led_max; i++) {
        rgb_matrix_set_color(i, r, g, b);
    }
    return false;
}

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3_ex2(  // base
        // Left: row0(6) + ex1
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Right: ex1 + row0(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Left: row1(6) + ex2
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Right: ex2 + row1(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Left: row2(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Right: row2(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Left: thumb(3)
        KC_NO, KC_NO, KC_NO,
        // Right: thumb(3)
        MO(1), MO(2), KC_NO
    ),

    [1] = LAYOUT_split_3x6_3_ex2(  // fx
        // Left: row0(6) + ex1
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Right: ex1 + row0(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Left: row1(6) + ex2
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Right: ex2 + row1(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Left: row2(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Right: row2(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Left: thumb(3)
        KC_NO, KC_NO, KC_NO,
        // Right: thumb(3)
        KC_NO, KC_NO, KC_NO
    ),

    [2] = LAYOUT_split_3x6_3_ex2(  // tape
        // Left: row0(6) + ex1
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Right: ex1 + row0(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Left: row1(6) + ex2
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Right: ex2 + row1(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Left: row2(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Right: row2(6)
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        // Left: thumb(3)
        KC_NO, KC_NO, KC_NO,
        // Right: thumb(3)
        KC_NO, KC_NO, QK_BOOT
    )
};
// clang-format on
